{
  "c": [
    {
      "actions": {
        "finish": [],
        "init": [],
        "start": []
      },
      "adjustedMax": "",
      "adjustedMin": "",
      "alpha": 1,
      "anchorFrameType": "SCREEN",
      "anchorPoint": "CENTER",
      "animation": {
        "finish": {
          "duration_type": "seconds",
          "easeStrength": 3,
          "easeType": "none",
          "type": "none"
        },
        "main": {
          "duration_type": "seconds",
          "easeStrength": 3,
          "easeType": "none",
          "type": "none"
        },
        "start": {
          "duration_type": "seconds",
          "easeStrength": 3,
          "easeType": "none",
          "type": "none"
        }
      },
      "authorOptions": [],
      "color": [
        1,
        1,
        1,
        1
      ],
      "conditions": [],
      "config": [],
      "cooldown": true,
      "cooldownEdge": true,
      "cooldownSwipe": true,
      "cooldownTextDisabled": true,
      "desaturate": false,
      "desc": "hi buff tracker for slice and dice for roguey, any spec",
      "frameStrata": 1,
      "height": 99.968376159668,
      "icon": true,
      "iconSource": -1,
      "id": "Slice n Dice Tracker",
      "information": [],
      "internalVersion": 82,
      "inverse": false,
      "keepAspectRatio": false,
      "load": {
        "class": {
          "multi": []
        },
        "class_and_spec": {
          "multi": [
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            true,
            true,
            true
          ],
          "single": 259
        },
        "size": {
          "multi": []
        },
        "spec": {
          "multi": []
        },
        "talent": {
          "multi": []
        },
        "use_class_and_spec": false
      },
      "progressSource": [
        -1,
        ""
      ],
      "regionType": "icon",
      "selfPoint": "CENTER",
      "semver": "1.0.0",
      "subRegions": [
        {
          "type": "subbackground"
        },
        {
          "anchorXOffset": 0,
          "anchorYOffset": 0,
          "anchor_point": "CENTER",
          "rotateText": "NONE",
          "text_automaticWidth": "Auto",
          "text_color": [
            1,
            1,
            1,
            1
          ],
          "text_fixedWidth": 64,
          "text_font": "Accidental Presidency",
          "text_fontSize": 18,
          "text_fontType": "OUTLINE",
          "text_justify": "CENTER",
          "text_selfPoint": "AUTO",
          "text_shadowColor": [
            0,
            0,
            0,
            1
          ],
          "text_shadowXOffset": 0,
          "text_shadowYOffset": 0,
          "text_text": "%p",
          "text_text_format_p_format": "timed",
          "text_text_format_p_time_dynamic_threshold": 60,
          "text_text_format_p_time_format": 0,
          "text_text_format_p_time_legacy_floor": false,
          "text_text_format_p_time_mod_rate": true,
          "text_text_format_p_time_precision": 1,
          "text_text_format_s_format": "none",
          "text_visible": true,
          "text_wordWrap": "WordWrap",
          "type": "subtext"
        },
        {
          "glow": true,
          "glowBorder": false,
          "glowColor": [
            1,
            1,
            1,
            1
          ],
          "glowDuration": 1,
          "glowFrequency": 0.25,
          "glowLength": 10,
          "glowLines": 8,
          "glowScale": 1,
          "glowThickness": 1,
          "glowType": "ACShine",
          "glowXOffset": 0,
          "glowYOffset": 0,
          "type": "subglow",
          "useGlowColor": false
        }
      ],
      "tocversion": 110007,
      "triggers": {
        "1": {
          "trigger": {
            "auranames": [
              "Slice and Dice"
            ],
            "debuffType": "HELPFUL",
            "event": "Health",
            "names": [],
            "spellIds": [],
            "subeventPrefix": "SPELL",
            "subeventSuffix": "_CAST_START",
            "type": "aura2",
            "unit": "player",
            "useName": true
          },
          "untrigger": []
        },
        "activeTriggerMode": -10
      },
      "uid": "hb99iQeu)Tk",
      "url": "https://wago.io/xLJrpiabZ/1",
      "useAdjustededMax": false,
      "useAdjustededMin": false,
      "useCooldownModRate": true,
      "version": 1,
      "wagoID": "xLJrpiabZ",
      "width": 99.04768371582,
      "xOffset": 17.52384185791,
      "yOffset": -17.984188079834,
      "zoom": 0
    }
  ],
  "d": {
    "actions": {
      "finish": [],
      "init": [],
      "start": []
    },
    "align": "CENTER",
    "alpha": 1,
    "anchorFrameType": "SCREEN",
    "anchorPoint": "CENTER",
    "animate": false,
    "animation": {
      "finish": {
        "duration_type": "seconds",
        "easeStrength": 3,
        "easeType": "none",
        "type": "none"
      },
      "main": {
        "duration_type": "seconds",
        "easeStrength": 3,
        "easeType": "none",
        "type": "none"
      },
      "start": {
        "duration_type": "seconds",
        "easeStrength": 3,
        "easeType": "none",
        "type": "none"
      }
    },
    "arcLength": 360,
    "authorOptions": [],
    "backdropColor": [
      1,
      1,
      1,
      0.5
    ],
    "border": false,
    "borderBackdrop": "Blizzard Tooltip",
    "borderColor": [
      0,
      0,
      0,
      1
    ],
    "borderEdge": "Square Full White",
    "borderInset": 1,
    "borderOffset": 4,
    "borderSize": 2,
    "centerType": "LR",
    "columnSpace": 1,
    "conditions": [],
    "config": [],
    "constantFactor": "RADIUS",
    "desc": "hi buff tracker for slice and dice for roguey, any spec",
    "frameStrata": 1,
    "fullCircle": true,
    "gridType": "RD",
    "gridWidth": 5,
    "grow": "DOWN",
    "id": "Slice n Dice Tracker - Roguey",
    "information": [],
    "internalVersion": 82,
    "limit": 5,
    "load": {
      "class": {
        "multi": []
      },
      "size": {
        "multi": []
      },
      "spec": {
        "multi": []
      },
      "talent": {
        "multi": []
      }
    },
    "radius": 200,
    "regionType": "dynamicgroup",
    "rotation": 0,
    "rowSpace": 1,
    "scale": 1,
    "selfPoint": "TOP",
    "semver": "1.0.0",
    "sort": "none",
    "sortHybridTable": {
      "Slice n Dice Tracker": false
    },
    "space": 2,
    "stagger": 0,
    "stepAngle": 15,
    "subRegions": [],
    "tocversion": 110007,
    "triggers": [
      {
        "trigger": {
          "debuffType": "HELPFUL",
          "event": "Health",
          "names": [],
          "spellIds": [],
          "subeventPrefix": "SPELL",
          "subeventSuffix": "_CAST_START",
          "type": "aura2",
          "unit": "player"
        },
        "untrigger": []
      }
    ],
    "uid": "sVeTEt(Zr3U",
    "url": "https://wago.io/xLJrpiabZ/1",
    "useLimit": false,
    "version": 1,
    "wagoID": "xLJrpiabZ",
    "xOffset": -451.01574707031,
    "yOffset": -364.15835571289
  },
  "m": "d",
  "s": "5.19.1",
  "v": 1421,
  "wagoID": "xLJrpiabZ"
}